profile_20.pref.adapter.connection.type=bluetooth
profile_20.pref.adapter.type=VGATE_VLINKER_MS
profile_20.pref.adapter.error.continue_on_error=true
profile_20.pref.adapter.power.switch_network_on_off=false
profile_20.pref.gauge_display_scale=false
profile_20.pref.gauge_display_command_rate=true
profile_20.pref.gauge_background_color=-14926478
profile_20.pref.gauge.fps="4"
profile_20.pref.adapter.power.start_data_logging.after="10"
profile_20.pref.adapter.id=
profile_20.pref.graph.view.enabled=true
profile_20.pref.adapter.init.delay_after_reset="500"
profile_20.pref.adapter.init.delay="500"
profile_20.pref.trips.recordings.save.short.trip=false
profile_20.pref.graph.x-axis.start-moving-after.time="20000"
profile_20.pref.toolbar.hide.connected=false
profile_20.pref.dash.background_color_1=-14926478
profile_20.pref.giulia.view.enabled=true
profile_20.pref.toolbar.hide.doubleclick=true
profile_20.pref.graph.trips.selected=
profile_20.pref.dash.swipe.to.delete=false
profile_20.pref.dash.top.values.red.color=false
profile_20.pref.pids.generic.high=[22, 7002, 13, 15, 7003, 7006, 6, 7005, 7018, 7029, 7007]
profile_20.pref.pids.generic.low=[7002, 7013, 7015, 15, 7003, 7014, 7017, 7016, 7027, 7020, 6, 7019, 7025]
profile_20.pref.gauge.pids.selected=[7003, 7008, 88007, 88006, 88005, 7009, 88004, 88003, 88001]
profile_20.pref.gauge.pids.selected.1=[7002, 7015, 7003, 7014, 7025, 6, 7005, 7016, 7019, 7018, 7029, 7020]
profile_20.pref.gauge.pids.selected.2=[7066, 7002, 7068, 7001, 7067, 7026, 7069, 7006, 7028, 7005, 7016, 7051, 7031, 7030, 7041, 7008, 7007, 17107]
profile_20.pref.gauge.pids.selected.3=[7002, 7013, 7003, 7025, 6]
profile_20.pref.gauge.pids.selected.4=[7015, 7014, 7019, 7020]
profile_20.pref.gauge.pids.selected.5=[7002, 7035, 7005, 7007]
profile_20.pref.gauge.pids.selected.6=[88007, 88006, 88005, 88004, 88003, 88001]
profile_20.pref.aa.gauge.pids.profile_1=[7002, 7015, 7003, 7014, 7025, 6, 7005, 7016, 7019, 7018, 7029, 7020]
profile_20.pref.aa.gauge.pids.profile_2=[7002, 7013, 7003, 7025, 6]
profile_20.pref.aa.gauge.pids.profile_3=[7015, 7014, 7019, 7020]
profile_20.pref.aa.gauge.pids.profile_4=[7002, 7035, 7005, 7007]
profile_20.pref.gauge.virtual.selected="1"
profile_20.pref.dash.view.enabled=false
profile_20.pref.adapter.cache.result.enabled=false
profile_20.pref.adapter.connection.tcp.host=192.168.0.10
profile_20.pref.adapter.connection.tcp.port="35000"
profile_20.pref.adapter.adaptive.enabled=false
profile_20.pref.dash.gauge.view.visible=false
profile_20.pref.graph.x-axis.minimum-shift.time="20"
profile_20.pref.profile.id=profile_20
profile_20.pref.adapter.power.screen_off=false
profile_20.pref.graph.cache.enabled=true
profile_20.pref.adapter.batch.enabled=true
profile_20.pref.adapter.stn.enabled=true
profile_20.pref.adapter.init.protocol=CAN_USER1
profile_20.pref.adapter.init.sequence=HS_CAN
profile_20.pref.adapter.command.freq="5"
profile_20.pref.adapter.power.connect_adapter=false
profile_20.pref.debug.generator.enabled=false
profile_20.pref.trips.recordings.display_info=false
profile_20.pref.dash.top.values.blink=false
profile_20.pref.graph.pids.selected=[88008, 88007, 88006, 88005, 88004, 88003, 88002, 88001, 88000]
profile_20.pref.graph.pids.selected.1=[88008, 88007, 88006, 88005, 88004, 88003, 88002, 88001, 88000]
profile_20.pref.gauge.view.enabled=true
profile_20.pref.toolbar.hide.landscape=false
profile_20.pref.dash.background_color_2=-14926478
pref.profile.names.profile_20=Alfa 2.0 GME (BT,STN, vLinker MS)
profile_20.pref.adapter.init.mode.selected=mode_1
profile_20.pref.adapter.init.mode.header_value.mode_2=18DA10F1
profile_20.pref.adapter.init.mode.id_value.mode_2="22"
profile_20.pref.adapter.init.mode.header_value.mode_1=18DB33F1
profile_20.pref.adapter.init.mode.id_value.mode_1="01"
profile_20.pref.adapter.init.mode.id="01"
profile_20.pref.adapter.init.mode.header=18DB33F1
profile_20.pref.adapter.init.mode.header_value.mode_4=18DA18F1
profile_20.pref.adapter.init.mode.id_value.mode_4="555"

profile_20.pref.adapter.init.mode.header_value.mode_5=18DA60F1
profile_20.pref.adapter.init.mode.id_value.mode_5="444"

profile_20.pref.adapter.init.mode.header_value.mode_6=18DAC7F1
profile_20.pref.adapter.init.mode.id_value.mode_6="666"

profile_20.pref.adapter.init.mode.header_value.mode_7=18DA60F1
profile_20.pref.adapter.init.mode.id_value.mode_7="INSTRUMENT_PANEL"

profile_20.pref.adapter.init.mode.header_value.mode_8=18DA28F1
profile_20.pref.adapter.init.mode.id_value.mode_8="ABS"

profile_20.pref.adapter.init.mode.header_value.mode_9=18DA1AF1
profile_20.pref.adapter.init.mode.id_value.mode_9="DTCM"

profile_20.pref.adapter.init.mode.header_value.mode_10=18DA10F1
profile_20.pref.adapter.init.mode.id_value.mode_10="GME20"

profile_20.pref.adapter.init.mode.header_value.mode_11=18DA98F1
profile_20.pref.adapter.init.mode.id_value.mode_11="TRW_CLIMATE_CONTROL"

profile_20.pref.adapter.init.fetchDeviceProperties=true
profile_20.pref.adapter.init.fetchSupportedPids=true
profile_20.pref.pids.registry.list=[2.0_gme_ext.json, trw_climate_control.json, giulia_2.0_gme.json]
profile_20.pref.datalogger.supported.pids=[]
profile_20.pref.adapter.graceful_stop.enabled=false
profile_20.pref.pids.registry.filter_pids_ecu_supported=false
profile_20.pref.pids.registry.filter_pids_stable=false

## Android Auto settings
profile_20.pref.aa.pids.selected=[7066, 7002, 7068, 7001, 7067, 7026, 7069, 7006, 7028, 7005, 7016, 7051, 7031, 7030, 7041, 7008, 7007, 17107]
profile_20.pref.aa.pids.profile_1=[7002, 7003, 7014, 7025, 6, 7005, 7016, 7019, 7018, 7029]
profile_20.pref.aa.pids.profile_2=[7002, 7003, 7025, 6]
profile_20.pref.aa.pids.profile_20=[7015, 7014, 7019, 7020]
profile_20.pref.aa.pids.profile_4=[7002, 7005, 7007]
profile_20.pref.aa.surface.fps="10"

#reconnect settings
profile_20.pref.adapter.reconnect=false
profile_20.pref.adapter.reconnect.max_retry="3"
profile_20.pref.profile.about=This profile contains Alfa Romeo 2.0 GME ECU specific settings adjusted to support Vgate Vlinker MS multiplexing capabilities.


profile_20.pref.giulia.pids.selected=[88008, 88007, 88006, 88005, 88004, 88003, 88002, 88001, 88000]
profile_20.pref.giulia.pids.selected.1=[22, 7035, 13, 7013, 7002, 15, 7014, 7003, 7025, 7006, 7017, 7005, 7027, 7016, 7020, 6, 7019, 7018, 7007, 7029]
profile_20.pref.giulia.pids.selected.2=[7066, 7002, 7068, 7001, 7067, 7026, 7069, 7006, 7028, 7005, 7016, 7051, 7031, 7030, 7041, 7008, 7007, 17107]
profile_20.pref.giulia.pids.selected.3=[88008, 88007, 88006, 88005, 88004, 88003, 88002, 88001, 88000]
profile_20.pref.adapter.batch_01.size="3"
profile_20.pref.adapter.batch.size="17"

profile_20.pref.profile.2_0_GME_extension.enabled=true
profile_20.pref.aa.trip_info.pids.selected=[7021, 7076, 7035, 7002, 7037, 7014, 7047, 7025, 7003, 7036, 7028, 7016, 17078, 7005, 7020, 7019, 7018, 7009]
profile_20.pref.aa.drag_race.debug.vehicle_speed_measurement=false

profile_20.pref.query.performance.break_boosting.gas_pid=7007
profile_20.pref.query.performance.break_boosting.arbitrary_pid=7028
profile_20.pref.query.performance.break_boosting.vehicle_speed_pid=7046

profile_20.pref.aa.performance.pids.selected=[7021, 7047, 7025, 7003, 7009, 7016, 7002, 7028, 7005, 7036, 7007]
profile_20.pref.query.performance.top=[7021, 7047, 7025, 7003, 7009, 7016, 7002, 7036, 17079, 7017, 7029, 7026, 7008, 7041, 17107, 17108]
profile_20.pref.query.performance.bottom=[7028, 7005, 7007, 7046, 17111]
profile_20.pref.query.performance.hidden=[7036]

profile_20.pref.adapter.query.individual.enabled=true
